// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhouxieyi.evaluationSiteOnContainers.BuildingBlocks.IntegrationEventLogEF;

#nullable disable

namespace IntegrationEventLogEF.Migrations
{
    [DbContext(typeof(IntegrationEventLogContext))]
    partial class IntegrationEventLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Zhouxieyi.evaluationSiteOnContainers.BuildingBlocks.IntegrationEventLogEF.IntegrationEventLogEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasComment("事件Id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("事件内容");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("记录时间");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("事件类型名");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasComment("事件状态: 2-发送执行成功 3-发送但执行失败");

                    b.Property<int>("TimesSent")
                        .HasColumnType("int")
                        .HasComment("发送次数");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("事务Id");

                    b.HasKey("EventId");

                    b.ToTable("IntegrationEventLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
