global using System.Text.Json.Serialization;
global using Zhouxieyi.evaluationSiteOnContainers.BuildingBlocks.EventBus.Abstractions;
global using Zhouxieyi.evaluationSiteOnContainers.BuildingBlocks.EventBus.Events;
global using Zhouxieyi.evaluationSiteOnContainers.BuildingBlocks.EventBus;
global using static Zhouxieyi.evaluationSiteOnContainers.BuildingBlocks.EventBus.InMemoryEventBusSubscriptionsManager;
