version: '3.9'

services:
  db_evaluation:
    image: mysql:8.0.27

  db_gamerepo:
    image: mysql:8.0.27

  db_indentity:
    image: mcr.microsoft.com/mssql/server:2019-latest

  db_backmanage:
    image: mysql:8.0.27

  mq_evaluation:
    image: rabbitmq:3.9.13-management

  cache_master:
    image: redis:6.2.6

  consul-server1:
    image: consul:1.9

  consul-server2:
    image: consul:1.9

  consul-server3:
    image: consul:1.9

  consul-client:
    image: consul:1.9
