global using System.Text.Json.Serialization;
global using Zhouxieyi.evaluationSiteOnContainers.BuildingBlocks.EventBusBase.Abstractions;
global using Zhouxieyi.evaluationSiteOnContainers.BuildingBlocks.EventBusBase.Events;
global using
    static Zhouxieyi.evaluationSiteOnContainers.BuildingBlocks.EventBusBase.InMemoryEventBusSubscriptionsManager;