version: '3.9'
services:
  db_evaluation:
    image: mysql:latest
    volumes:
      - mysql_evaluation:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Zhoushan!1n
    ports:
      - "3306:3306"

  db_gamerepo:
    image: mysql:latest
    volumes:
      - mysql_gamerepo:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Gam2Rep0!!
    ports:
      - "3307:3306"

  mq_evaluation:
    image: rabbitmq:3.9.13-management
    volumes:
      - rabbitmq_evaluation:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=zhoushanlin
      - RABBITMQ_DEFAULT_PASS=rabbitmq!!..
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  mysql_gamerepo:
  mysql_evaluation:
  rabbitmq_evaluation:
