version: '3.9'

services:
  db_evaluation:
    volumes:
      - mysql_evaluation:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Zhoushan!1n
    ports:
      - "3306:3306"

  db_gamerepo:
    volumes:
      - mysql_gamerepo:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Gam2Rep0!!
    ports:
      - "3307:3306"

  db_indentity:
    environment:
      - SA_PASSWORD=Zh0u!1,,
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_identity:/var/opt/mssql

  db_backmanage:
    volumes:
      - mysql_backmanage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ZhouBack!1n
    ports:
      - "3308:3306"

  mq_evaluation:
    volumes:
      - rabbitmq_evaluation:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=zhoushanlin
      - RABBITMQ_DEFAULT_PASS=rabbitmq!!..
    ports:
      - "15672:15672"
      - "5672:5672"

  cache_master:
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass zhouredis11..
    volumes:
      - redis_master:/data

  gateway_web:
    volumes:
      - ./ApiGateways/Envoy/config/envoy.yaml:/etc/envoy/envoy.yaml
      - ./ApiGateways/Envoy/logs:/var/log
    ports:
      - 9901:9901
      - 10000:10000
    environment:
      - "ENVOY_UID=0"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__IdentityConnection=Server=db_indentity;Database=IdentityDb;User Id=sa;Password=Zh0u!1,,;
      - ConnectionStrings__IntegrationConnection=Server=db_indentity;Database=IntegrationDb;User Id=sa;Password=Zh0u!1,,;
      - EventBusSettings__Connection=mq_evaluation
      - EventBusSettings__UserName=zhoushanlin
      - EventBusSettings__PassWord=rabbitmq!!..
      - EvaluationApiClient=http://localhost:5100
      - GameRepoApiClient=http://localhost:5101
      - OrderingApiClient=http://localhost:5102
      - BackManageApiClient=http://localhost:5104
      - IdentityUrl=http://localhost:5105
    ports:
      - "5105:80"

  evaluation-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__EvaluationDbConnectString=server=db_evaluation;port=3306;database=game_evaluation;user=root;password=Zhoushan!1n;IgnoreCommandTransaction=true
      - EventBusSettings__Connection=mq_evaluation
      - EventBusSettings__UserName=zhoushanlin
      - EventBusSettings__PassWord=rabbitmq!!..
      - IdentityUrlExternal=http://localhost:5105
      - IdentityUrl=http://localhost:5105
      - PATH_BASE=/evaluation-api
      - UseCustomizationData=True
      - SwaggerRedirectUrlPort=5100
    ports:
      - "5100:80"

  #容器内通讯使用容器开放的端口 而不是映射到主机的端口
  gamerepo-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__GameRepoDbConnectString=server=db_gamerepo;port=3306;database=game_information;user=root;password=Gam2Rep0!!;IgnoreCommandTransaction=true
      - ConnectionStrings__GameStoreDbConnectString=server=db_gamerepo;port=3306;database=game_store;user=root;password=Gam2Rep0!!;IgnoreCommandTransaction=true
      - ConnectionStrings__IntegrationDbConnectString=server=db_gamerepo;port=3306;database=game_integration;user=root;password=Gam2Rep0!!;IgnoreCommandTransaction=true
      - EventBusSettings__Connection=mq_evaluation
      - EventBusSettings__UserName=zhoushanlin
      - EventBusSettings__PassWord=rabbitmq!!..
      - Redis__Hosts__0__Host=cache_master
      - Redis__Hosts__0__Port=6379
      - RedisHCCheckConnection=cache_master,DefaultDatabase=0,password=zhouredis11..
      - IdentityUrlExternal=http://localhost:5105
      - IdentityUrl=http://localhost:5105
      - PATH_BASE=/gamerepo-api
      - GRPC_PORT=81
      - PORT=80
      - SwaggerRedirectUrlPort=5101
    ports:
      - "5101:80"
      - "9101:81"

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Redis__Hosts__0__Host=cache_master
      - Redis__Hosts__0__Port=6379
      - RedisHCCheckConnection=cache_master,DefaultDatabase=0,password=zhouredis11..
      - IdentityUrlExternal=http://localhost:5105
      - IdentityUrl=http://localhost:5105
      - GameRepoUrl=http://gamerepo-api
      - GrpcGameRepoUrl=http://gamerepo-api:81
      - PATH_BASE=/ordering-api
      - GRPC_PORT=81
      - PORT=80
      - SwaggerRedirectUrlPort=5102
    ports:
      - "5102:80"
      - "9102:81"

  backmanage-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - BackDbConnectString=server=db_backmanage;port=3306;database=evaluation_back;user=root;password=ZhouBack!1n;IgnoreCommandTransaction=true
      - IdentityUrlExternal=http://localhost:5105
      - IdentityUrl=http://localhost:5105
      - PATH_BASE=/backmanage-api
      - SwaggerRedirectUrlPort=5104
    ports:
      - "5104:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=Evaluation Services Check
      - HealthChecksUI__HealthChecks__0__Uri=http://evaluation-api/hc
      - HealthChecksUI__HealthChecks__1__Name=GameRepository Services Check
      - HealthChecksUI__HealthChecks__1__Uri=http://gamerepo-api/hc
      - HealthChecksUI__HealthChecks__2__Name=Ordering Services Check
      - HealthChecksUI__HealthChecks__2__Uri=http://ordering-api/hc
      - HealthChecksUI__HealthChecks__3__Name=BackManager Services Check
      - HealthChecksUI__HealthChecks__3__Uri=http://backmanage-api/hc
      - HealthChecksUI__HealthChecks__4__Name=Identity Services Check
      - HealthChecksUI__HealthChecks__4__Uri=http://identity-api/hc
    ports:
      - "5106:80"
volumes:
  mysql_gamerepo:
  mysql_evaluation:
  mysql_backmanage:
  mssql_identity:
  rabbitmq_evaluation:
  redis_master:
